const api = window.killwind;
const $ = (selector) => document.querySelector(selector);
const LEVEL_LABELS = { Info: '信息', Success: '成功', Warning: '警告', Error: '错误' };
const STATUS_LABELS = { Connected: '已连接', Disconnected: '未连接', Scanning: '扫描中', Ready: '就绪' };
const els = {
  processSelect: $('#processSelect'), refreshProcesses: $('#refreshProcesses'), launchTestGame: $('#launchTestGame'), screenEdit: $('#screenEdit'), attach: $('#attachProcess'), detach: $('#detachProcess'),
  statusDot: $('#statusDot'), statusText: $('#statusText'), processName: $('#processName'), processPid: $('#processPid'), processArch: $('#processArch'), processMemory: $('#processMemory'), processStarted: $('#processStarted'), processPath: $('#processPath'),
  scanValue: $('#scanValue'), firstScan: $('#firstScan'), nextScan: $('#nextScan'), cancelScan: $('#cancelScan'), newScan: $('#newScan'), scanState: $('#scanState'), scanCount: $('#scanCount'), scanProgress: $('#scanProgress'), scanProgressText: $('#scanProgressText'), scanElapsed: $('#scanElapsed'),
  resultsBody: $('#resultsBody'), addSelected: $('#addSelected'), addressBody: $('#addressBody'), refreshAddresses: $('#refreshAddresses'), regionsBody: $('#regionsBody'), regionSummary: $('#regionSummary'), profileName: $('#profileName'), saveProfile: $('#saveProfile'), profileSelect: $('#profileSelect'), loadProfile: $('#loadProfile'), logList: $('#logList'),
  screenEditModal: $('#screenEditModal'), closeScreenEdit: $('#closeScreenEdit'), cancelScreenEdit: $('#cancelScreenEdit'), applyScreenEdit: $('#applyScreenEdit'), screenEditHint: $('#screenEditHint'), screenCurrentValue: $('#screenCurrentValue'), screenNewValue: $('#screenNewValue'),
};
let processes = []; let attached = null; let scan = null; let selectedResults = new Set(); let screenEditActive = false;

function log(level, message, metadata) {
  const row = document.createElement('div'); row.className = `log-entry ${level.toLowerCase()}`;
  const time = new Date().toLocaleTimeString('zh-CN', { hour12: false });
  row.innerHTML = `<span class="log-time">${time}</span><span class="log-level">${LEVEL_LABELS[level] || level}</span><span></span>`;
  row.lastElementChild.textContent = `${message}${metadata ? ` · ${JSON.stringify(metadata)}` : ''}`;
  els.logList.prepend(row); while (els.logList.children.length > 80) els.logList.lastElementChild.remove();
}
function setStatus(status, message) {
  els.statusDot.className = `status-dot ${status === 'Connected' ? 'connected' : status === 'Scanning' ? 'scanning' : 'disconnected'}`;
  els.statusText.textContent = message || STATUS_LABELS[status] || status; els.scanState.textContent = status === 'Connected' ? '就绪' : STATUS_LABELS[status] || status;
}
function formatBytes(value) { const n = Number(value || 0); if (n < 1024) return `${n} B`; if (n < 1024 ** 2) return `${(n / 1024).toFixed(1)} KB`; if (n < 1024 ** 3) return `${(n / 1024 ** 2).toFixed(1)} MB`; return `${(n / 1024 ** 3).toFixed(2)} GB`; }
function formatStart(value) { if (!value) return '—'; const date = new Date(value); return Number.isNaN(date.getTime()) ? '—' : date.toLocaleString('zh-CN', { hour12: false }); }
function renderProcesses() {
  const selected = attached?.pid || Number(els.processSelect.value); els.processSelect.innerHTML = '<option value="">选择一个进程…</option>';
  processes.forEach((process) => { const option = document.createElement('option'); option.value = process.pid; option.textContent = `${process.name} · PID ${process.pid} · ${process.architecture}`; option.dataset.process = JSON.stringify(process); els.processSelect.append(option); });
  if (selected && processes.some((item) => item.pid === selected)) els.processSelect.value = selected;
}
async function refreshProcesses() { try { processes = await api.processes(); renderProcesses(); log('Info', '进程列表已刷新', { count: processes.length }); } catch (error) { log('Error', error.message); } }
function renderProcess(process) { attached = process; const fields = [['processName', process?.name || '—'], ['processPid', process?.pid || '—'], ['processArch', process?.architecture || '—'], ['processMemory', process ? formatBytes(process.memoryBytes) : '—'], ['processStarted', formatStart(process?.startTime)], ['processPath', process?.path || '—']]; fields.forEach(([key, value]) => { els[key].textContent = value; }); els.detach.disabled = !process; els.firstScan.disabled = !process; els.saveProfile.disabled = !process; els.screenEdit.disabled = !process; setStatus(process ? 'Connected' : 'Disconnected'); }
function renderRegions(regions) { els.regionSummary.textContent = `${regions.length} 个区域`; els.regionsBody.innerHTML = ''; if (!regions.length) { els.regionsBody.innerHTML = '<tr><td colspan="4" class="empty">没有可读取的内存区域。</td></tr>'; return; } regions.slice(0, 400).forEach((region) => { const row = document.createElement('tr'); row.innerHTML = `<td>${region.baseAddress}</td><td>${formatBytes(region.size)}</td><td>${region.protection}</td><td>${region.type}${region.executable ? ' · 执行' : ''}${region.writable ? ' · 写入' : ''}</td>`; els.regionsBody.append(row); }); }
function renderResults() { els.resultsBody.innerHTML = ''; const results = scan?.results || []; els.scanCount.textContent = `${results.length.toLocaleString()} 个结果`; if (!results.length) { els.resultsBody.innerHTML = '<tr><td colspan="6" class="empty">没有匹配地址。</td></tr>'; els.addSelected.disabled = true; return; } results.slice(0, 2000).forEach((result, index) => { const row = document.createElement('tr'); if (selectedResults.has(index)) row.classList.add('selected'); row.innerHTML = `<td><input type="checkbox" data-result-index="${index}" ${selectedResults.has(index) ? 'checked' : ''}></td><td>${result.address}</td><td>${result.value}</td><td>${result.type}</td><td>${result.module || '—'}</td><td><button class="mini-button" data-add-index="${index}">添加</button></td>`; els.resultsBody.append(row); }); els.addSelected.disabled = selectedResults.size === 0; }
async function renderAddresses() { const entries = await api.readAddresses(); els.addressBody.innerHTML = ''; if (!entries.length) { els.addressBody.innerHTML = '<tr><td colspan="6" class="empty">请从扫描结果添加变量。</td></tr>'; return; } entries.forEach((entry) => { const row = document.createElement('tr'); row.innerHTML = `<td><input class="address-input desc-input" data-desc-id="${entry.id}" value=""></td><td title="${entry.address}">${entry.address}</td><td class="${entry.status === 'Invalid' ? 'status-invalid' : 'status-resolved'}">${entry.value ?? '—'}</td><td><input class="address-input" data-value-id="${entry.id}" value="${entry.value ?? ''}"></td><td><input class="freeze-check" type="checkbox" data-freeze-id="${entry.id}" ${entry.frozen ? 'checked' : ''} aria-label="冻结 ${entry.address}"></td><td><button class="mini-button" data-write-id="${entry.id}">写入</button><button class="mini-button" data-remove-id="${entry.id}">×</button></td>`; row.querySelector(`[data-desc-id="${entry.id}"]`).value = entry.description; els.addressBody.append(row); }); }
async function attach() { const process = processes.find((item) => item.pid === Number(els.processSelect.value)); if (!process) return log('Warning', '请选择目标进程。'); try { const result = await api.attach(process); renderProcess(result.process); renderRegions(result.regions); els.profileName.value = result.process.name.replace(/\.exe$/i, ''); log('Success', '已连接进程', result.process); } catch (error) { log('Error', error.message); } }
async function startScan(next = false) { if (!attached) return; try { selectedResults.clear(); setStatus('Scanning'); els.cancelScan.disabled = false; els.firstScan.disabled = true; els.nextScan.disabled = true; els.scanProgress.style.width = '0%'; els.scanProgressText.textContent = next ? '正在过滤上一轮结果…' : '正在读取可提交内存区域…'; const result = next ? await api.nextScan(els.scanValue.value) : await api.firstScan(els.scanValue.value); scan = result; renderResults(); els.nextScan.disabled = false; els.scanProgressText.textContent = `${result.scannedBytes ? formatBytes(result.scannedBytes) : '0 B'} 已扫描 · ${result.results.length.toLocaleString()} 个结果`; els.scanElapsed.textContent = `${result.elapsedMs} ms`; setStatus('Connected'); log('Success', next ? '再次扫描完成' : '首次扫描完成', { results: result.results.length, elapsedMs: result.elapsedMs }); } catch (error) { setStatus('Connected'); log('Error', error.message); } finally { els.cancelScan.disabled = true; els.firstScan.disabled = !attached; els.nextScan.disabled = !scan; } }
async function addResult(result) { try { await api.addAddress(result); await renderAddresses(); log('Info', '已添加地址', { address: result.address }); } catch (error) { log('Error', error.message); } }
async function saveProfile() { try { const profile = await api.saveProfile({ gameName: els.profileName.value || attached.name, executable: attached.name, executablePath: attached.path, architecture: attached.architecture }); await loadProfiles(); log('Success', '配置已保存', { gameName: profile.gameName }); } catch (error) { log('Error', error.message); } }
async function loadProfiles() { const names = await api.profileList(); els.profileSelect.innerHTML = '<option value="">选择已保存配置</option>'; names.forEach((name) => { const option = document.createElement('option'); option.value = name; option.textContent = name; els.profileSelect.append(option); }); }
async function loadProfile() { if (!els.profileSelect.value) return; try { const profile = await api.loadProfile(els.profileSelect.value); els.profileName.value = profile.gameName; await renderAddresses(); log('Success', '配置已加载', { gameName: profile.gameName }); } catch (error) { log('Error', error.message); } }

function closeScreenEdit() { screenEditActive = false; els.screenEditModal.hidden = true; els.screenEdit.disabled = !attached; els.screenEdit.textContent = '屏幕取值模式'; }
async function startScreenEdit() { if (!attached) return; screenEditActive = true; els.screenEdit.disabled = true; els.screenEdit.textContent = '请在游戏中点击数字…'; log('Info', '屏幕取值模式已开启，请点击游戏画面中的数字。'); try { const point = await api.pickScreenPoint(); els.screenEditHint.textContent = `已捕获屏幕坐标 (${point.x}, ${point.y})。请输入画面上的 Int32 数值。`; els.screenCurrentValue.value = ''; els.screenNewValue.value = ''; els.screenEditModal.hidden = false; els.screenCurrentValue.focus(); } catch (error) { log('Warning', error.message); closeScreenEdit(); } }
async function applyScreenEdit() { try { els.applyScreenEdit.disabled = true; const result = await api.applyScreenEdit({ currentValue: els.screenCurrentValue.value, newValue: els.screenNewValue.value }); if (result.status === 'applied') { log('Success', '画面数值已修改', result); closeScreenEdit(); await refreshAddresses(); return; } if (result.status === 'not-found') { log('Warning', '没有找到匹配的 Int32 数值。'); els.screenEditHint.textContent = '没有找到匹配值，请检查画面当前数值后重试。'; return; } scan = { results: result.results }; renderResults(); els.screenEditHint.textContent = `找到 ${result.totalResults.toLocaleString()} 个匹配项，请在结果列表中选择并写入。`; log('Warning', '屏幕数值存在多个匹配项', { count: result.totalResults }); } catch (error) { log('Error', error.message); } finally { els.applyScreenEdit.disabled = false; } }

els.refreshProcesses.addEventListener('click', refreshProcesses); els.launchTestGame.addEventListener('click', async () => { try { await api.launchTestGame(); log('Info', '测试游戏已启动'); setTimeout(refreshProcesses, 800); } catch (error) { log('Error', error.message); } }); els.screenEdit.addEventListener('click', startScreenEdit); els.closeScreenEdit.addEventListener('click', closeScreenEdit); els.cancelScreenEdit.addEventListener('click', closeScreenEdit); els.applyScreenEdit.addEventListener('click', applyScreenEdit); els.attach.addEventListener('click', attach); els.detach.addEventListener('click', async () => { await api.detach(); closeScreenEdit(); renderProcess(null); renderRegions([]); scan = null; renderResults(); await renderAddresses(); }); els.firstScan.addEventListener('click', () => startScan(false)); els.nextScan.addEventListener('click', () => startScan(true)); els.cancelScan.addEventListener('click', () => api.cancelScan()); els.newScan.addEventListener('click', async () => { await api.clearScan(); scan = null; selectedResults.clear(); renderResults(); els.nextScan.disabled = true; els.scanProgress.style.width = '0%'; els.scanProgressText.textContent = '已准备新扫描。'; els.scanElapsed.textContent = '—'; }); els.addSelected.addEventListener('click', async () => { for (const index of selectedResults) await addResult(scan.results[index]); }); els.refreshAddresses.addEventListener('click', renderAddresses); els.saveProfile.addEventListener('click', saveProfile); els.loadProfile.addEventListener('click', loadProfile);
els.resultsBody.addEventListener('change', (event) => { const index = Number(event.target.dataset.resultIndex); if (!Number.isInteger(index)) return; if (event.target.checked) selectedResults.add(index); else selectedResults.delete(index); event.target.closest('tr').classList.toggle('selected', event.target.checked); els.addSelected.disabled = selectedResults.size === 0; }); els.resultsBody.addEventListener('click', (event) => { const index = Number(event.target.dataset.addIndex); if (Number.isInteger(index)) addResult(scan.results[index]); });
els.addressBody.addEventListener('click', async (event) => { const writeId = event.target.dataset.writeId; const removeId = event.target.dataset.removeId; try { if (writeId) { const value = event.target.closest('tr').querySelector(`[data-value-id="${writeId}"]`).value; await api.updateAddress({ id: writeId, value }); await renderAddresses(); log('Success', 'Write Success', { value }); } if (removeId) { await api.removeAddress(removeId); await renderAddresses(); } } catch (error) { log('Error', error.message); } }); els.addressBody.addEventListener('change', async (event) => { const freezeId = event.target.dataset.freezeId; const descId = event.target.dataset.descId; try { if (freezeId) { await api.freezeAddress({ id: freezeId, frozen: event.target.checked, intervalMs: 100 }); log('Info', event.target.checked ? 'Freeze enabled' : 'Freeze disabled'); } if (descId) await api.updateAddress({ id: descId, description: event.target.value }); } catch (error) { log('Error', error.message); } });
api.on('scan:progress', (progress) => { if (progress.totalBytes) els.scanProgress.style.width = `${Math.min(100, progress.scannedBytes / progress.totalBytes * 100)}%`; if (progress.phase === 'warning') log('Warning', progress.message); else { els.scanProgressText.textContent = `${formatBytes(progress.scannedBytes)} / ${formatBytes(progress.totalBytes)} · ${progress.resultCount.toLocaleString()} results`; els.scanElapsed.textContent = `${progress.elapsedMs} ms`; } }); api.on('process:state', (state) => { if (state.process) { renderProcess(state.process); } else { renderProcess(null); log('Warning', state.message || 'Process Closed'); } }); api.on('freeze:event', (event) => { if (event.type === 'freeze-error') log('Error', event.message); });

refreshProcesses(); loadProfiles(); renderAddresses(); log('Info', 'KillWind 已就绪 · 仅用于离线本地进程');
